#services:
#  redis:
#    image: redis:7.2
#    container_name: redis_cache
#    ports:
#      - "6379:6379"
#    command: [ "redis-server", "--bind", "0.0.0.0", "--appendonly", "yes" ]
#    volumes:
#      - redis_data:/data
#
#  redisinsight:
#    image: redis/redisinsight:latest
#    container_name: redis_insight
#    ports:
#      - "8001:5540"
#    depends_on:
#      - redis

services:
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
#  redis_data:
